name = "katallaxie"
license = "MIT"
licenselink = "https://github.com/katallaxie/hugo-katallaxie/blob/master/LICENSE"
description = ""
homepage = "https://katallaxie.dev/"
tags = []
features = []
min_version = "0.41.0"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[author]
  name = "Sebastian Döll"
  homepage = "https://katallaxie.dev"
  avatar = "images/avatar.png"

features = [
  "theme-toggle"
]

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
