baseURL = ''
languageCode = 'en-us'
title = 'Sebastian Döll | Head of PaaS Internal Services at IONOS'
description = 'Sebastian Döll Head of PaaS Internal Services at IONOS. Crafting software with great user experiences.'

theme = 'katallaxie'

[build]
  writeStats = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup]
  [markup.highlight]
    style = 'vim'
    noClasses = false