baseURL = 'https://katallaxie.dev/'
languageCode = 'en-us'
title = 'Sebastian Döll | Senior Software Engineer'

theme = 'katallaxie'

[build]
  writeStats = true

[markup]
  [markup.highlight]
    style = 'vim'
    noClasses = false