baseURL = ''
languageCode = 'en-us'
title = 'Sebastian Döll | Head of PaaS Internal Services at IONOS Cloud'

theme = 'katallaxie'

[build]
  writeStats = true

[markup]
  [markup.highlight]
    style = 'vim'
    noClasses = false