baseURL = ''
languageCode = 'en-us'
title = 'Sebastian Döll | Engineer with decades of experience'
enableRobotsTXT = true
theme = 'katallaxie'

[params]
  description = 'Sebastian Döll is a snarky engineer in the cloud. Crafting software with great user experiences.'

  [[params.color]]
    name= "red"
    weight = 10
  
  [[params.color]]
    name= "green"
    weight = 10

  [[params.color]]
    name= "yellow"
     weight = 10
  
  [[params.color]]
    name= "blue"
    weight = 20
  
  [[params.color]]
    name= "purple"
    weight = 20

[build]
  writeStats = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup]
  [markup.highlight]
    style = 'vim'
    noClasses = false

[taxonomies]
  category = 'categories'
  tag = 'tags'
